std = "lua51"
max_line_length = false

-- Generated by UpdateForeverBiS.py; not hand-written code.
exclude_files = { "ForeverBiS/ForeverBiS_Data.lua" }

-- Layering is enforced by what each layer can see: a file that reaches for an API outside its layer fails
-- luacheck as an undefined variable. Core (pure logic) sees none of the client API, Adapters are the only
-- callers of the item, inventory and unit APIs, and only Settings.lua touches the saved variables.

-- Addon data and the legacy globals the model builds from it; every layer may read them.
local addon_data = { "ForeverBiSData", "ForeverBiSModel", "ForeverBiSLists", "ForeverBiSItemIDs", "ForeverBiSBuildLabels" }

local function with(...)
  local merged = {}
  for _, list in ipairs({ addon_data, ... }) do
    for _, name in ipairs(list) do
      table.insert(merged, name)
    end
  end
  return merged
end

local widget_api = {
  "CreateFrame",
  "GameTooltip",
  "UIParent",
  "STANDARD_TEXT_FONT",
  "UIDropDownMenu_AddButton",
  "UIDropDownMenu_CreateInfo",
  "UIDropDownMenu_Initialize",
  "UIDropDownMenu_SetText",
  "UIDropDownMenu_SetWidth",
}

read_globals = with(widget_api)

files["ForeverBiS/ForeverBiS_Model.lua"] = {
  read_globals = { "ForeverBiSData" },
  globals = { "ForeverBiSModel", "ForeverBiSLists", "ForeverBiSItemIDs", "ForeverBiSBuildLabels" },
}

files["ForeverBiS/ForeverBiS_Locale.lua"] = { read_globals = { "GetLocale" } }

files["ForeverBiS/Core/"] = { read_globals = with() }
files["ForeverBiS/Core/Settings.lua"] = { read_globals = with(), globals = { "ForeverBiSDB", "ForeverBiSCharDB" } }

files["ForeverBiS/Adapters/Items.lua"] = {
  read_globals = with({ "C_Item", "GetItemIcon", "GetItemInfo", "GetItemInfoInstant", "ITEM_QUALITY_COLORS" }),
}
files["ForeverBiS/Adapters/Inventory.lua"] = { read_globals = with({ "GetInventoryItemID", "GetItemCount" }) }
files["ForeverBiS/Adapters/Chat.lua"] = {
  read_globals = with({ "ChatEdit_InsertLink", "IsInGroup", "IsInRaid", "IsShiftKeyDown", "SendChatMessage" }),
}
files["ForeverBiS/Adapters/Player.lua"] = {
  read_globals = with({ "GetRealmName", "UnitClass", "UnitFactionGroup", "UnitFullName", "UnitLevel", "UnitName" }),
}

files["ForeverBiS/UI/"] = { read_globals = with(widget_api, { "Minimap", "GetCursorPosition", "RAID_CLASS_COLORS" }) }

files["ForeverBiS/App/Events.lua"] = { read_globals = with(widget_api, { "C_Timer" }) }
files["ForeverBiS/App/Commands.lua"] = {
  read_globals = with(),
  globals = { "SlashCmdList", "SLASH_FOREVERBIS1", "SLASH_FOREVERBIS2" },
}

-- The tooltip decorator hooks the client's tooltip APIs directly and publishes its own global.
files["ForeverBiS/ForeverBiS_Tooltip.lua"] = {
  read_globals = with({
    "C_Item",
    "Enum",
    "ForeverBiSFrame",
    "GameTooltip",
    "GetItemInfo",
    "ItemRefTooltip",
    "TooltipDataProcessor",
    "UnitClass",
    "UnitLevel",
  }),
  globals = { "ForeverBiSTooltip" },
}

files["tests/"] = {
  std = "+busted",
  globals = { "_G", "WowStub", "ForeverBiSMinimapButton", "ForeverBiSData", "ForeverBiSDB", "ForeverBiSCharDB", "ForeverBiSTooltip" },
  -- Frames the addon registers by name through CreateFrame.
  read_globals = {
    "ItemRefTooltip",
    "SlashCmdList",
    "ForeverBiSFrame",
    "ForeverBiSClassDropDown",
    "ForeverBiSBuildDropDown",
    "ForeverBiSDungeonFilter",
    "ForeverBiSFilterquest",
    "ForeverBiSFilterdungeon",
    "ForeverBiSFilterworld",
    "ForeverBiSFilterprofession",
    "ForeverBiSFilterFaction",
    "ForeverBiSFilterMaker",
    "ForeverBiSPhaseDropDown",
  },
}
