std = "lua51"
max_line_length = false

-- Generated by UpdateForeverBiS.py; not hand-written code.
exclude_files = { "ForeverBiS/ForeverBiS_Data.lua" }

globals = {
  "ForeverBiSDB",
  "SLASH_FOREVERBIS1",
  "SLASH_FOREVERBIS2",
  "SlashCmdList",
}

-- WoW client API and data tables used by the addon.
read_globals = {
  "C_Item",
  "CreateFrame",
  "GameTooltip",
  "GetCursorPosition",
  "GetInventoryItemID",
  "GetItemCount",
  "GetItemIcon",
  "GetItemInfo",
  "GetItemInfoInstant",
  "GetRealmName",
  "ITEM_QUALITY_COLORS",
  "Minimap",
  "RAID_CLASS_COLORS",
  "STANDARD_TEXT_FONT",
  "UIDropDownMenu_AddButton",
  "UIDropDownMenu_CreateInfo",
  "UIDropDownMenu_Initialize",
  "UIDropDownMenu_SetText",
  "UIDropDownMenu_SetWidth",
  "UIParent",
  "UnitClass",
  "UnitFullName",
  "UnitLevel",
  "UnitName",
  "ForeverBiSLists",
  "ForeverBiSItemIDs",
  "ForeverBiSBuildLabels",
}

files["tests/"] = {
  std = "+busted",
  globals = { "_G", "WowStub", "ForeverBiSMinimapButton" },
  -- Frames the addon registers by name through CreateFrame.
  read_globals = {
    "ForeverBiSFrame",
    "ForeverBiSClassDropDown",
    "ForeverBiSBuildDropDown",
    "ForeverBiSFactionFilter",
    "ForeverBiSSourceFilter",
  },
}
