-- Guards the shape of the data generated by UpdateForeverBiS.py: the addon indexes it blindly.
describe("ForeverBiS_Data", function()
    setup(function()
        assert(loadfile("ForeverBiS/ForeverBiS_Data.lua"))()
    end)

    it("defines the three global tables", function()
        assert.is_table(ForeverBiSLists)
        assert.is_table(ForeverBiSItemIDs)
        assert.is_table(ForeverBiSBuildLabels)
    end)

    it("has a title and at least one slot for every list", function()
        for key, list in pairs(ForeverBiSLists) do
            assert.is_string(list.title, key)
            assert.is_true(#list.slots > 0, key .. " has no slots")
        end
    end)

    it("gives every slot a name and ranked items with a source", function()
        for key, list in pairs(ForeverBiSLists) do
            for _, slot in ipairs(list.slots) do
                local where = key .. "/" .. tostring(slot[1])
                assert.is_string(slot[1], where)
                assert.is_true(#slot[2] > 0, where .. " has no items")
                for _, item in ipairs(slot[2]) do
                    assert.is_string(item[1], where)
                    assert.is_string(item[2], where .. " " .. tostring(item[1]))
                end
            end
        end
    end)

    it("stores enchants as {effect, spell, source[, formula item id]}", function()
        local total = 0
        for key, list in pairs(ForeverBiSLists) do
            for _, slot in ipairs(list.slots) do
                for _, enchant in ipairs(slot[3] or {}) do
                    local where = key .. "/" .. slot[1]
                    total = total + 1
                    assert.is_string(enchant[1], where)
                    assert.is_true(enchant[1] ~= "", where .. " has an empty effect")
                    assert.is_string(enchant[2], where)
                    assert.is_string(enchant[3], where)
                    assert.is_true(enchant[4] == nil or type(enchant[4]) == "number", where)
                end
            end
        end
        assert.is_true(total > 0, "no enchants found in any list")
    end)

    it("keeps the item id map numeric", function()
        for name, itemID in pairs(ForeverBiSItemIDs) do
            assert.is_string(name)
            assert.is_number(itemID)
        end
    end)

    it("labels every build route that has a list", function()
        for route in pairs(ForeverBiSBuildLabels) do
            assert.is_not_nil(ForeverBiSLists[route], "label without a list: " .. route)
        end
    end)
end)
