-- Guards the shape of the data generated by UpdateForeverBiS.py (schema 2): the model indexes it blindly.
local VALID_KINDS = { quest = true, profession = true, dungeon = true, world = true, unknown = true }

describe("ForeverBiS_Data", function()
    setup(function()
        assert(loadfile("ForeverBiS/ForeverBiS_Data.lua"))()
    end)

    local function eachPhase(visit)
        for route, list in pairs(ForeverBiSData.lists) do
            for phaseId, phase in pairs(list.phases) do
                visit(route, phaseId, phase)
            end
        end
    end

    it("defines schema 2 and no legacy globals", function()
        assert.are.equal(2, ForeverBiSData.schema)
        assert.is_table(ForeverBiSData.phases)
        assert.is_table(ForeverBiSData.lists)
    end)

    it("orders phases oldest first with unique ids", function()
        local seen, previousLevel = {}, nil
        for _, phase in ipairs(ForeverBiSData.phases) do
            assert.is_string(phase.id)
            assert.is_string(phase.label)
            assert.is_nil(seen[phase.id], "duplicate phase " .. phase.id)
            seen[phase.id] = true
            if phase.level then
                assert.is_number(phase.level)
                assert.is_true(previousLevel == nil or phase.level >= previousLevel, "phases out of order")
                previousLevel = phase.level
            end
        end
        assert.is_true(#ForeverBiSData.phases > 0)
    end)

    it("gives every list a label and phases that are declared in `phases`", function()
        local declared = {}
        for _, phase in ipairs(ForeverBiSData.phases) do
            declared[phase.id] = true
        end
        for route, list in pairs(ForeverBiSData.lists) do
            assert.is_string(list.label, route)
            assert.is_true(next(list.phases) ~= nil, route .. " has no phase")
            for phaseId in pairs(list.phases) do
                assert.is_true(declared[phaseId], route .. " uses undeclared phase " .. tostring(phaseId))
            end
        end
    end)

    it("has a title and at least one slot for every phase", function()
        eachPhase(function(route, phaseId, phase)
            assert.is_string(phase.title, route .. "/" .. phaseId)
            assert.is_true(#phase.slots > 0, route .. "/" .. phaseId .. " has no slots")
        end)
    end)

    it("gives every slot a name and ranked items with a structured source", function()
        eachPhase(function(route, phaseId, phase)
            for _, slot in ipairs(phase.slots) do
                local where = route .. "/" .. phaseId .. "/" .. tostring(slot.slot)
                assert.is_string(slot.slot, where)
                assert.is_true(#slot.items > 0, where .. " has no items")
                for _, item in ipairs(slot.items) do
                    assert.is_string(item.name, where)
                    assert.is_true(item.id == nil or type(item.id) == "number", where .. " " .. item.name)
                    assert.is_table(item.source, where .. " " .. item.name)
                    assert.is_true(VALID_KINDS[item.source.kind], where .. " bad kind " .. tostring(item.source.kind))
                    assert.is_string(item.source.text, where .. " " .. item.name)
                end
            end
        end)
    end)

    it("stores enchants as {effect, spell, source[, formulaId]}", function()
        local total = 0
        eachPhase(function(route, _, phase)
            for _, slot in ipairs(phase.slots) do
                if slot.enchants ~= nil then
                    assert.is_true(#slot.enchants > 0, route .. "/" .. slot.slot .. " has an empty enchants table")
                end
                for _, enchant in ipairs(slot.enchants or {}) do
                    local where = route .. "/" .. slot.slot
                    total = total + 1
                    assert.is_string(enchant.effect, where)
                    assert.is_true(enchant.effect ~= "", where .. " has an empty effect")
                    assert.is_string(enchant.spell, where)
                    assert.is_string(enchant.source, where)
                    assert.is_true(enchant.formulaId == nil or type(enchant.formulaId) == "number", where)
                end
            end
        end)
        assert.is_true(total > 0, "no enchants found in any list")
    end)
end)
