local function loadSettings(db, labels)
    WowStub.reset()
    _G.ForeverBiSDB = db
    _G.ForeverBiSBuildLabels = labels
    WowStub.loadFiles({ "ForeverBiS_Data.lua", "ForeverBiS_Model.lua", "Core/Settings.lua", "Core/Catalog.lua" })
    return WowStub.ns.Settings
end

describe("Settings", function()
    after_each(function()
        _G.ForeverBiSDB, _G.ForeverBiSBuildLabels = nil, nil
    end)

    describe("bind", function()
        it("creates the saved variables with the rogue as the default class", function()
            local Settings = loadSettings(nil)
            Settings.bind()
            assert.are.equal("rogue", ForeverBiSDB.class)
            assert.are.equal("pve", ForeverBiSDB.build)
            assert.is_table(ForeverBiSDB.minimap)
            assert.is_table(ForeverBiSDB.collapsed)
        end)

        it("keeps what the client already loaded", function()
            local collapsed = { ["druid:Head"] = true }
            local Settings = loadSettings({ class = "druid", build = "tank", collapsed = collapsed })
            Settings.bind()
            assert.are.equal("druid", ForeverBiSDB.class)
            assert.are.equal(collapsed, ForeverBiSDB.collapsed)
        end)

        it("replaces a collapsed value that is not a table", function()
            local Settings = loadSettings({ collapsed = "broken" })
            Settings.bind()
            assert.are.same({}, ForeverBiSDB.collapsed)
        end)

        it("follows a saved variables table the client swaps in later", function()
            local Settings = loadSettings({ class = "mage" })
            Settings.bind()
            _G.ForeverBiSDB = { class = "hunter" }
            Settings.bind()
            assert.are.equal("hunter", Settings.classKey())
        end)
    end)

    describe("get", function()
        it("reads a saved value", function()
            local Settings = loadSettings({ tooltip = false })
            assert.is_false(Settings.get("tooltip"))
        end)

        it("returns nil while the saved variables are unavailable", function()
            local Settings = loadSettings(nil)
            assert.is_nil(Settings.get("tooltip"))
        end)
    end)

    describe("route", function()
        it("writes the resolved class and build back and returns the route", function()
            local Settings = loadSettings({ class = "not-a-class", build = "not-a-build" })
            local route, class, build = Settings.route()
            assert.are.equal("rogue", route)
            assert.are.equal("rogue", class.key)
            assert.are.equal("", build[1]) -- the default build has an empty route suffix
            assert.are.equal("rogue", ForeverBiSDB.class)
            assert.are.equal("", ForeverBiSDB.build)
        end)

        it("includes the build suffix", function()
            local Settings = loadSettings({ class = "druid", build = "/tank" })
            assert.are.equal("druid/tank", (Settings.route()))
        end)
    end)

    describe("class and build choices", function()
        it("chooses a class with its default build and stops auto-detection", function()
            local Settings = loadSettings({ class = "rogue", build = "/pvp" })
            Settings.chooseClass(WowStub.ns.Catalog.findClass("druid"))
            assert.are.equal("druid", ForeverBiSDB.class)
            assert.are.equal("", ForeverBiSDB.build)
            assert.is_true(ForeverBiSDB.classChosen)
        end)

        it("chooses a build without touching the class", function()
            local Settings = loadSettings({ class = "druid", build = "feral-pve" })
            Settings.chooseBuild("/tank")
            assert.are.equal("druid", Settings.classKey())
            assert.are.equal("/tank", Settings.buildKey())
        end)

        it("detects the player's class and resets the build only when the class changes", function()
            local Settings = loadSettings({ class = "rogue", build = "/pvp" })
            Settings.applyDetectedClass("DRUID")
            assert.are.equal("druid", ForeverBiSDB.class)
            assert.are.equal("", ForeverBiSDB.build)
            ForeverBiSDB.build = "/tank"
            Settings.applyDetectedClass("DRUID")
            assert.are.equal("/tank", ForeverBiSDB.build)
        end)

        it("does not detect over a class chosen by hand", function()
            local Settings = loadSettings({ class = "rogue", build = "pve", classChosen = true })
            Settings.applyDetectedClass("DRUID")
            assert.are.equal("rogue", ForeverBiSDB.class)
        end)

        it("ignores a missing or unknown class token", function()
            local Settings = loadSettings({ class = "rogue", build = "pve" })
            Settings.applyDetectedClass(nil)
            Settings.applyDetectedClass("DEATHKNIGHT")
            assert.are.equal("rogue", ForeverBiSDB.class)
        end)
    end)

    describe("phase", function()
        it("stores and clears the chosen phase", function()
            local Settings = loadSettings({})
            Settings.choosePhase("lvl30")
            assert.are.equal("lvl30", Settings.phase())
            Settings.choosePhase(nil)
            assert.is_nil(Settings.phase())
        end)

        it("drops a saved phase the route does not have", function()
            local Settings = loadSettings({ phase = "no-such-phase" })
            Settings.dropUnavailablePhase("rogue")
            assert.is_nil(Settings.phase())
        end)

        it("shows the phase for the player's level when none is saved", function()
            local Settings = loadSettings({})
            assert.are.equal(ForeverBiSModel.effectivePhase("rogue", nil, 30), Settings.effectivePhase("rogue", 30))
        end)
    end)

    describe("collapsed sections", function()
        it("toggles and expands sections", function()
            local Settings = loadSettings({})
            Settings.bind()
            assert.is_false(Settings.isCollapsed("rogue:Head"))
            Settings.toggleCollapsed("rogue:Head")
            assert.is_true(Settings.isCollapsed("rogue:Head"))
            Settings.toggleCollapsed("rogue:Head")
            assert.is_false(Settings.isCollapsed("rogue:Head"))
            Settings.toggleCollapsed("rogue:Head")
            Settings.expand("rogue:Head")
            assert.is_false(Settings.isCollapsed("rogue:Head"))
        end)
    end)

    describe("minimap", function()
        it("defaults to 220 degrees and visible", function()
            local Settings = loadSettings({})
            assert.are.equal(220, Settings.minimapAngle())
            assert.is_false(Settings.minimapHidden())
        end)

        it("stores the angle and honors the hide flag", function()
            local Settings = loadSettings({ minimap = { hide = true } })
            Settings.setMinimapAngle(90)
            assert.are.equal(90, Settings.minimapAngle())
            assert.is_true(Settings.minimapHidden())
        end)
    end)

    describe("tooltip", function()
        it("is on by default and toggles", function()
            local Settings = loadSettings({})
            assert.is_true(Settings.tooltipEnabled())
            assert.is_false(Settings.toggleTooltip())
            assert.is_false(Settings.tooltipEnabled())
            assert.is_true(Settings.toggleTooltip())
        end)

        it("shows other classes only after toggling them on", function()
            local Settings = loadSettings({})
            assert.is_false(Settings.tooltipAllClasses())
            assert.is_true(Settings.toggleTooltipAllClasses())
            assert.is_true(Settings.tooltipAllClasses())
            assert.is_false(Settings.toggleTooltipAllClasses())
        end)
    end)
end)
